# Air 設定
[build]
bin = "main"      # コンパイルされたバイナリ名
cmd = "go build -o main ."  # ビルドコマンド
include_ext = ["go"]        # ウォッチ対象の拡張子
exclude_dir = ["frontend"]  # ウォッチしないディレクトリ

[log]
time = true                 # ログにタイムスタンプを表示
